const services = [
  {
    id: 1,
    iconKey: "ScanLine",
    title: "Hazard & Pothole Reporting",
    tag: "Civic Surveillance",
    frontDesc: "Report potholes, blind turns, road hazards, and garbage hotspots with live GPS.",
    backTitle: "Smart Reporting Suite",
    backDetails: [
      "Multi-category reporting: Potholes, Blind Turns & Waste",
      "Instant GPS coordinate capture & severity rating",
      "Automated task allocation for municipal road & sanitation crews",
      "Real-time ticket tracking from reported to resolved",
    ],
    route: "/upload",
  },
  {
    id: 2,
    iconKey: "Bot",
    title: "AI Waste Detection",
    tag: "Computer Vision",
    frontDesc: "YOLOv8 deep learning model for automated waste classification.",
    backTitle: "Smart AI Technology",
    backDetails: [
      "Real-time visual waste classification",
      "Automatic detection of litter and bin overflows",
      "Precision confidence scoring on camera captures",
      "Eliminates manual triage delays",
    ],
    route: "/upload",
  },
  {
    id: 3,
    iconKey: "Users",
    title: "Community Engagement",
    tag: "Civic Action",
    frontDesc: "Join local resident communities for collaborative neighborhood cleanups.",
    backTitle: "Civic Communities",
    backDetails: [
      "Create & join localized cleanliness ward groups",
      "Coordinate volunteer cleaning drives",
      "Host neighborhood awareness sessions",
      "Foster accountability with public scorecards",
    ],
    route: "/committee",
  },
  {
    id: 4,
    iconKey: "Calendar",
    title: "Event Hosting & Participation",
    tag: "Field Drives",
    frontDesc: "Host environmental workshops, join cleanups, and earn GreenCoins.",
    backTitle: "Community Events Hub",
    backDetails: [
      "Organize citizen-led cleanup drives",
      "Host educational waste segregation workshops",
      "One-click attendee registration & attendance",
      "Earn verified GreenCoins for every drive attended",
    ],
    route: "/events",
  },
  {
    id: 5,
    iconKey: "ShoppingBag",
    title: "E-commerce Platform",
    tag: "Circular Economy",
    frontDesc: "Redeem earned GreenCoins for eco-friendly supplies and tools.",
    backTitle: "Green Marketplace",
    backDetails: [
      "Spend earned GreenCoins directly on goods",
      "Subsidized compost bins and segregation kits",
      "High-durability safety gloves & collection tools",
      "Partnered with sustainable civic suppliers",
    ],
    route: "/shop",
  },
  {
    id: 6,
    iconKey: "GraduationCap",
    title: "Training & Learning",
    tag: "Education",
    frontDesc: "Educational video guides, interactive simulations, and chatbot assistance.",
    backTitle: "Interactive Learning",
    backDetails: [
      "Curated video library on 3-way segregation",
      "Interactive Recycling Game for all ages",
      "Hazardous & bio-medical waste handling protocols",
      "Civic quiz modules to earn bonus points",
    ],
    route: "/training",
  },
  {
    id: 7,
    iconKey: "Recycle",
    title: "Waste Franchise Mediator",
    tag: "Authorized Recycling",
    frontDesc: "Channel e-waste and batteries to certified recyclers for cash rewards.",
    backTitle: "Certified Recycling Network",
    backDetails: [
      "Certified e-waste collection network",
      "Lithium battery and hazardous drop-offs",
      "Direct mediation with authorized recycling hubs",
      "Monetary compensation for recyclable items",
    ],
    route: "/recycle",
  },
  {
    id: 8,
    iconKey: "Coins",
    title: "GreenCoins Rewards System",
    tag: "Gamified Civic Action",
    frontDesc: "Gamified incentives rewarding verified citizen cleanliness actions.",
    backTitle: "Earn & Redeem Ecosystem",
    backDetails: [
      "Earn tokens for reporting validated hotspots",
      "Bonus multiplier for community cleanup attendance",
      "Instant balance updates with blockchain-ready audit",
      "Redeem for marketplace items or merchant discounts",
    ],
    route: "/shop",
  },
  {
    id: 9,
    iconKey: "Trophy",
    title: "Activity Leaderboard",
    tag: "Citizen Recognition",
    frontDesc: "Compete across wards and rank based on verified contributions.",
    backTitle: "Civic Hall of Fame",
    backDetails: [
      "Ward-level and city-wide rankings",
      "Total GreenCoins & cleanup drive milestones",
      "Badges for top contributors and active students",
      "Promotes positive civic competition",
    ],
    route: "/profile",
  },
  {
    id: 10,
    iconKey: "ShieldCheck",
    title: "Admin Management",
    tag: "Municipal Control",
    frontDesc: "Central command center for automated dispatch, reports, and events.",
    backTitle: "Command & Control",
    backDetails: [
      "Smart routing for municipal sanitation trucks",
      "Verification queue for citizen event proposals",
      "Role-based access for OSP officers & officials",
      "Comprehensive city cleanliness analytics",
    ],
    route: "/officials",
  },
];

export default services;
